- BNomad/View/PlaceInfoView/PlaceInfoViewController.swift
하프모달, 풀모달, 애니메이션 모달뷰 구현 했습니다.
- #3
- ## 작업 내용
- UISheetPresentationController를 이용해 하프모달-풀모달을 제스처를 통한 닫기 기능 까지 구현했습니다. 
- UISheetPresentationController는 ios 15부터 사용 가능한 기능으로 이하 버전에서는 사용이 불 가능 합니다. 해당 기능을 이용하면 모달 구현시 코드가 상당히 간단해집니다. 하지만 15이하의 버전에서도 사용해야 한다면 코드를 변경해야합니다. 
- https://gonslab.tistory.com/m/71
UISheetPresentationController 기능 구현시 참고한 블로그입니다.
> [Feat] #3 PlaceInfoview Modal 구현

- BNomad/BNomad.entitlements
- #49 
- sprint1에서 사용하지 않는 애플로그인을 빼줍니다.
> [Setting] #49 sign in apple 삭제

- BNomad.xcodeproj/project.pbxproj
- BNomad/Application/ViewController.swift
- BNomad/View/MapView/MapData.swift
- BNomad/View/MapView/MapViewController.swift
- BNomad/View/MapView/PlaceAnnotation.swift
- BNomad/View/PlaceCheckInView/CheckedProfileListHeader.swift
- BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
- BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
- BNomad/View/PlaceCheckInView/UserProfileViewCell.swift
- BNomad/View/PlaceInfoView/BasicInfoCell.swift
- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
- BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
- BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
- BNomad/View/ProfileView/ProfileViewController.swift
- BNomad/View/ProfileView/SelfUserInfoCell.swift
- BNomad/View/SignUpView/SignUpViewController.swift
- #59 
- ViewController 사이의 데이터 바인딩보다도 각자 view에서 User, Place, CheckIn 객체 기반으로 연결하기.
- User, Place, CheckIn 객체의 더미데이터 선언해서 하드코딩된 부분 제거 (객체의 속성 적극 사용)
- 객체 안에 없는 속성은 상단에 임의로 변수 선언 후 사용. ex) Place 객체 안에 이용시간, 금액 변수 없음
- 객체내에 있는 옵셔널 속성 처리 주의!, forced unwrapping(!) 하지 않기. guard let, if let 적극 사용.
- 변수 상태에 따른 분기 처리
- 버튼에 firebase CRUD 함수 붙이기
> [Feat] 데이터 연결을 위한 리팩토링

- BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
- BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
- #67 
- 현재 위치의 위도, 경도 값, 그리고 장소들의 위도, 경도 값들을 사용해서 각 워크스페이스들 까지의 거리를 계산하는 함수를 작성했습니다.
- 각 워크스페이스들에서 사람들의 평균 근무 시간을 계산하는 함수를 작성했습니다.
- 업무 공간 갯수, 워크스페이스들의 이름, 거리, 현재 체크인한 사람 수, 평균 근무 시간 데이터를 view 랑 연결했습니다.
- 현재 data 에 currentCheckIn, totalCheckInHistory, todayCheckInHistory 데이터가 nil 값이어서 평균 근무 시간과 현재 체크인한 사람 수 데이터가 불러와지지 않습니다. 후에 data 가 채워지면 다시 평균 근무 시간 계산 함수의 작동 여부를 확인할 예정입니다.
- MapView 에 sheet.position = currentLocation 코드 추가해주세요.
- https://stackoverflow.com/questions/27928/calculate-distance-between-two-latitude-longitude-points-haversine-formula
> [Feat] #67 PlaceViewBeforeCheckIn 에서의 데이터 연결

- BNomad/Model/DummyData.swift
- BNomad/Model/User.swift
- BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
- BNomad/View/PlaceCheckInView/CheckedProfileListHeader.swift
- BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
- BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
- BNomad/View/PlaceCheckInView/UserProfileViewCell.swift
- #62 
- 해당 공간에 체크인한 사용자 프로필 업데이트
- 기본 프로필, 체크인 시간, 이용시간 등
- 이용시간을 나타내는 상태바는 디자인 변경 가능성이 있어 보류하였습니다. 
- 체크아웃하기 버튼은 이어서 작업하겠습니다. 
- 해당 공간 기본 정보 업데이트
- 축약된 위치정보(예: 제주시->포항시), 누적근무시간 추후 변경
- 사용자 프로필 상태바가 어떤 정보를 담으면 좋을지 디자인 논의가 필요합니다 (2차 스프린트) 
- 이용시간의 경우 해당 사용자의 최근 체크인 시간을 불러온 뒤 현재시간과 비교하여 차이를 나타내고 있습니다. 해당 공간에 체크인했는지, 언제 했는지, 이미 체크아웃을 한 게 아닌지 등을 고려한 로직으로 변경해야 할 것 같습니다.
> [Feat] #62 PlaceCheckInView 데이터 연결

- BNomad/Application/CombineViewModel.swift
- BNomad/View/MapView/MapViewController.swift
- #77 
- viewModel과 MapViewController 연결합니다.
- viewWillAppear에 문제가 있는 것 같아서 주석처리했습니다.
- 
> [Feat] viewModel과 MapViewController 연결

- BNomad/Application/AppDelegate.swift
- BNomad/View/MapView/MapViewController.swift
- #75 
- 체크인 UI와 그 기능을 완성했습니다.
- 앱을 끄고 다시 켜도 시간은 계속 흐르게 됩니다.
- MapViewController에 Timer 추가되어서 한번 봐주세요!
- https://developer.apple.com/forums/thread/114859
> [Feat] #75 체크인 이후의 타이머 UI와 기능을 완성했습니다.

- BNomad/View/SignUpView/SignUpViewController.swift
> [Feat] SignUpView 나가기 버튼 추가

- BNomad/Application/ViewController.swift
- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- #84 
- checkIn 함수를 구현했습니다.
- user 객체에 체크인 데이터 추가
- 파이어베이스에 체크인 데이터 업로드
- checkOut 함수를 구현했습니다.
- user의 currentCheckIn에 checkOutTime 업로드
- 파이어베이스에 체크아웃 타임 업로드
> [feat] checkIn, checkOut 함수 구현

- BNomad/View/MapView/MapViewController.swift
- 맵 어노테이션에 모달 드래그 디스미스 할 때 (will dismiss) 디셀렉트 하는 함수 추가
- #98 
- 맵 어노테이션에 모달 드래그 디스미스 할 때 (will dismiss) 디셀렉트 하는 함수 추가
> [bug] 모달 디스미스 버그 수정

- BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
- BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
- #87 
- CustomModalView에 체크인 인원, 평균시간, 거리 정보를 firebase에서 불러와서 띄웁니다.
> [Feat] #87 CustomModalView에 체크인 인원, 평균시간, 거리 불러와서 띄우기

- BNomad/View/MapView/MapViewController.swift
- BNomad/View/PlaceInfoView/PlaceInfoCell.swift
- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
CustomModalViewController에 현재 위치 전달하기, 이어지는 PlaceInfoModalView 로 데이터 전달하기
- #91 
- MapView 로부터 CustomModalViewController 에 currentLocation 데이터 전달
- CustomModalViewController 에서 PlaceInfoModalView 로 place 데이터 전달
- place 에서의 currentCheckIn 과 totalCheckInHistory 데이터가 들어오면 PlaceInfoModalView 로 평균 근무 시간과 현재 체크인된 사람들 수 데이터를 전달해야 할 것 같습니다.
> [Feat] #91 CustomModalViewController에 현재 위치 전달하기, 이어지는 PlaceInfoModalView 로 데이터 전달하기

- BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
- 체크 아웃한 사람이 없을 때 뜨는 crush를 수정했습니다.
> [Fix] placeInfoModal에 뜨는 정보 수정 

- BNomad/View/ProfileView/CalendarViewController.swift
- BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
- BNomad/View/ProfileView/ProfileViewController.swift
- 생명주기 관련 내비게이션 버그를 수정했습니다.
- 프로필뷰 이하의 appear 관련 생명주기를 삭제
- 맵뷰의 appear 생명주기에 내비게이션 함수 추가
> [Fix]내비게이션 버그 픽스

- BNomad/Application/SceneDelegate.swift
- BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- #107 
- 맵뷰에서 선택한 장소 데이터를 받아서 뷰에 구현하였습니다. 
- 이전에 작업한 데이터 중 삭제할 부분이 있는지 체크 부탁드립니다. 패치를 다시 받아오는 것이 맞는지 검토 중 입니다. 
-
> [Feat] #107 맵뷰에서 선택된 장소로 데이터 연결

- BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
- #105 
- 10월 26일로 고정되어 있던 날짜를 Date()로 수정하였습니다.....
> [Fix] #105 함께 일하는 노마더 명수 수정

- BNomad/View/PlaceInfoView/PlaceInfoCell.swift
- BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
- #106 
- 평균 근무 시간과 현재 체크인 된 사람 수 데이터를 PlaceInfoModalViewController 에 전달 (MapView 의 annotation 에서 넘어가는 PlaceInfoModalView 와 리스트 보기 버튼을 통해 넘어가는 PlaceInfoModalView)
> [Feat] #106 PlaceInfoModalViewController 에 평균 근무 시간과 현재 체크인 된 사람 수 데이터 연결

- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
리팩토링은 내일의 나에게,,,
- #109 
- 체크인 체크아웃을 위한 함수와 체크를 해주었습니다,,
- 동일한 코드 두번작성 죄송합니다,,,
> [Feat] #109 체크인, 체크아웃!

- BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
- BNomad/View/ProfileView/ProfileViewController.swift
#89 
- profileViewController viewModel 연결하기]
- placeCheckInVIewController를 viewModel과 연결합니다
> [Feat] viewModel 연결하기

- BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
- BNomad/View/ProfileView/ProfileViewController.swift
- BNomad/View/ProfileView/SelfUserInfoCell.swift
- 프로필 수정 후 파이어베이스에 업로드
- 프로필 수정 후 viewModel.user 수정
> [feat] 프로필 수정 후 파이어베이스에 업로드 & 뷰 반영

- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
-체크 아웃 메세지 수정 했습니다.
- #134 
- 체크아웃 얼럿메세지 수정 
> [chore]MapViewPlaceInfoView 코드 정리 및 표출되는 메세지 수정

- BNomad.xcodeproj/project.pbxproj
- BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
- BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
- 체크인하고 나오는 풀모달에서 체크아웃시, 나오는 Alert작업을 했습니다.
- 프로젝트파일의 iOS버전 최소를 15.5 -> 15.0으로 통일했습니다.(Button.configure, Model.detent로 15로 맞춰야함)
> [Feat] ListCellView에서 checkOut관련 로직을 만들었습니다 + iOS 최저 15로 버전 통일

- BNomad/View/MapView/MapViewController.swift
- #97 
- 디바이스 위치 중심으로 맵뷰 시작
- 체크인 시 체크인된 장소 중심으로 시작 구현은 실패...
> [Feat] 앱 시작 시 현재 위치 중심으로 시작

- BNomad.xcodeproj/project.pbxproj
- FirebasePerformance : 성능 체크를 위해서
- FirebaseRemoteConfig : a/b 테스팅을 위해서
> [setting] firebase 라이브러리를 추가합니다

- BNomad.xcodeproj/project.pbxproj
- BNomad/Application/SceneDelegate.swift
- BNomad/Utils/RCValue.swift
- BNomad/View/MapView/MapViewController.swift
- BNomad/View/SignUpView/SignUpViewController.swift
- A/B testing 변수를 설정하는 remote Config를 구성했습니다.  (RCValue 클래스 생성)
- isLoginFirst를 조건으로 시작시 signUpView present
- Firebase A/B Testing 구성 (firebase 콘솔 참고)
- signUpView 진입과 완료시 이벤트 로그
- https://www.kodeco.com/20974552-firebase-tutorial-ios-a-b-testing
- https://www.kodeco.com/17323848-firebase-remote-config-tutorial-for-ios
- https://firebase.google.com/docs/ab-testing
> [Feat] signUp 시점 A/B 테스트 구현

- BNomad/View/ProfileView/CalendarViewController.swift
- BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
- BNomad/View/ProfileView/ProfileGraphCollectionCell.swift
- BNomad/View/ProfileView/VisitingInfoCell.swift
- 비짓카드의 레이블이 하나만 나오던 것을 분기처리를 통해 캘린더뷰에서는 클릭한 셀에 해당하는 레이블이 정상 표기되도록 하였다
- 매 월 1~9일의 비짓카드가 나오지 않던 문제를 해결했다
- 외 버그픽스
> [Fix]프로필뷰 오토레이아웃 수정 및 버그픽스

- BNomad.xcodeproj/project.pbxproj
- BNomad/View/MapView/MapViewController.swift
- BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
- BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
- #150
- Modal View 내에서 현위치에서의 거리에 따라 순서 변경
- Modal View 뒤에 있는 화면 (MapView) 를 클릭하면 Modal View 가 내려가게 수정
- 거리에 따른 순서 변경을 하는 방법이 매번 계산을 새로 해서 View 를 로드하는데 시간이 좀 걸려서 다른 방법도 고려해봐야 할 것 같습니다
> [Feat] #150 PlaceViewBeforeCheckIn 피드백 반영해서 수정

- BNomad.xcodeproj/project.pbxproj
- BNomad/View/PlaceInfoView/PlaceInfoCell.swift
- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- BNomad/View/PlaceInfoView/ReviewInfoCell.swift
- #160 
- 컴포넌트 위치 조정 및 삭제, 구현
- 기존에 존재하는 데이터와 관련된 컴포넌트는 바인딩 완료
- 퀘스트  관련 레이블은 더미로 구현 -2번째 셀 이름 UI변경에 따른 네이밍 변경
-
> [Feat]PlaceInfoCell UI변경

- BNomad.xcodeproj/project.pbxproj
- BNomad/Utils/Extensions/UIColor+Extension.swift
- BNomad/View/MeetUpView/MeetUpViewController.swift
- BNomad/View/MeetUpView/ParticipantCell.swift
- #159 
- 퀘스트 내용을 보는 뷰 입니다.
- 데이터 연결 없이 우선 단순 UI 작업했습니다.
- UIColor extension의 기존 nomadBlue 컬러를 새로 바뀐 컬러 코드로 수정했습니다.
- 작성자 프로필 사진 위의 crown은 추후 `isWriter` 등을 이용해서 작성자가 아닌 경우 hidden하는 것으로 생각하고 있습니다.
- 없음
> [Feat] #159 MeetUpView UI 작업입니다.

- BNomad.xcodeproj/project.pbxproj
- BNomad/API/FirebaseManager.swift
- BNomad/API/FirebaseTestVC.swift
- BNomad/Model/MeetUp.swift
- #171 
- meetUp 모델 생성
- 특정 사람의 참석한 meetUpUid 가져오기
- 특정 장소의 당일 meetUp 데이터 가져오기
- meetUp 생성하기
- meetUp 참석하기
- 생성한 meetUp 수정하기
- 생성한 meetUp 삭제하기
- meetUp 참석 취소하기
- 필요한 api가 빠지지 않았는지?
- 더 적합한 변수명 추천 부탁드립니다!
> [Feat] meetUp 모델 생성, 관련된 firebase api 구현

- BNomad/View/PlaceInfoView/PlaceInfoCell.swift
- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- #164 
- chevron 버튼을 통해 사이즈 자동 확장 기능 구현
> [feat]OperatingTimeLable Expandable sizing 구현

- BNomad/View/PlaceCheckInView/CheckedProfileListHeader.swift
- BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
- BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
- #183 
- PlaceCheckInViewController에 체크인한 사람들의 cell과 그 header UI를 작업했습니다.
- ~~피그마에 있는 값으로 했는데, 리스트의 shadow가 느낌상 조금 진한 것 같아 확인 한번 해주시면 감사하겠슴다🫡~~
- ~~위와 유사하게 사람들의 한마디(CheckedProfileListViewCell의 noteLabel) 역시 색상이 조금 진한 것 같네요.~~
- [c4489bc](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-NoPower/pull/186/commits/c4489bc101318058d8ef7d6358f4df5565e0ced0) 에서 반영완료
수정전
수정후
> [Feat] CheckInListProfile , Header UI 완성

- BNomad/API/FirebaseManager.swift
- BNomad/View/SettingView/PlaceRequestViewController.swift
#212
- 장소제안시 firebase realtime database에 Dummy/service/suggestPlace로 업로드
- 장소 제안 button과 연결 완료
- @sunshiningsoo 상호명, 주소가 입력되지 않았을 때 alert가 뜨는 것이 필요합니다!
> [Feat] suggest place

- BNomad/API/FirebaseManager.swift
#214 
- firebase realtime database의 dummy/service/withdrawal에 탈퇴사유를 업로드 합니다.
> [Feat] firebase에 탈퇴 사유 업로드

- BNomad.xcodeproj/project.pbxproj
- BNomad/API/FirebaseManager.swift
- BNomad/Model/Review.swift
- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- BNomad/View/PlaceInfoView/ReviewInfoCell.swift
- BNomad/View/PlaceInfoView/ReviewSubCell/ReviewSubCell.swift
close #173 
- Review 모델을 추가했습니다.
- 리뷰와 관련된 firebase api 를 구현했습니다.
- PlaceInfoModalViewController 뷰에 데이터 바인딩을 했습니다.
- @Willowwryu 
- 리뷰의 개수에 따라서 다이나믹한 높이 변화가 필요할 것 같습니다. 
- UI 수정이 필요합니다
- 디테일한 데이터 바인딩이 필요합니다! (ex. 방문자 수)
|리뷰 4개일 때 |리뷰 3개일 때|
|--|--|
|<img width="300" alt="image" src="https://user-images.githubusercontent.com/59302419/201523305-7bb61528-efb3-4da2-bf0f-a873df38b277.png">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/59302419/201523645-80f6dfb8-a5fa-4fef-af45-221c6fde18ca.png">|
> [Feat] review 모델 생성 & firebase api & 데이터 바인딩

- BNomad/View/MapView/MapViewController.swift
- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- #225 
- 체크인 alert 프로퍼티로 빼서 외부 함수에서 접근 가능하도록 변곁
- 텍스트 실시간 변경에 따라 alert의 확인 버튼 enabled 변경 (목표를 입력해야 확인버튼 클릭 가능)
- 데이터모델은 임의로 추가하지 않고 우선 print로 값을 받을 수 있는지만 확인했습니다.
> [Feat] 체크인 시 textfield 구현

- BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
- BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
- 누락된 프로필 이미지 바인딩을 했습니다
|before|after|
|-|-|
|<img width="300" alt="image" src="https://user-images.githubusercontent.com/59302419/202335860-76ab2c8c-c5a0-466f-9bf2-24825e244d1e.png">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/59302419/202335630-35adcf4a-49ff-4f2c-952d-b9dda2fdec86.png">|
> [Feat] 프로필 이미지 바인딩

- BNomad.xcodeproj/project.pbxproj
- BNomad/Utils/Extensions/String+Extension.swift
- BNomad/View/ReviewView/ReviewCell.swift
- BNomad/View/ReviewView/ReviewListViewController.swift
- #232 
- ReviewListViewController 의 Cell 안에 있는 리뷰의 길이와 사진의 유무에 따라서 cell height 를 dynamically 조정하는 기능을 추가했습니다.
- 디자이너와의 회의 이후 더보기 버튼을 없애고 전부 펼쳐놓기로 하여 일단은 펼치고 여는 기능을 지우고 dynamic height 기능을 추가했습니다. 추후에 더보기 기능이 필요하다 느껴지면 다시 추가할 예정입니다.
> [Feat] #232 ReviewListViewController 에 Dynamic Cell Height 추가

- BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
- BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
- #264 
- CustomModalView UI를 업데이트된 프로토타입 UI에 맞게 작업했습니다.
- 스팟별 밋업 개수가 추가되고, 평균 근무시간이 삭제되었습니다.
- 
-
> [Enhancement] #264 CustomModalView UI 업데이트

- BNomad/View/MapView/MapViewController.swift
- #253 
- 체크인 시 버튼 노출, 상단 바 색상 변경 구현
- 체크인 한 장소와 시간 바인딩이 아직 불안정해서 계속 수정 예정
> [Feat] 체크인 버튼 구현

- BNomad/View/PlaceInfoView/PlaceInfoCell.swift
- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- BNomad/View/PlaceInfoView/ReviewInfoCell.swift
- BNomad/View/PlaceInfoView/ReviewSubCell/ReviewSubCell.swift
- #269 
- 그래버 변경
- 리뷰 이미지, 프로필 이미지뷰에 .scaleAspectFill 추가
> [chore]1차 출시 이전 마지막 ui수정

- BNomad/View/LoginView/LoginViewController.swift
- BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
- #271 
- 체크아웃시에 속한 밋업에서 나오는 로직 작성
- 로그아웃 이후 로그인시, checkInHistory fetch
> [Enhancement] #271 CheckIn History fetch, logout

- BNomad/API/FirebaseManager.swift
- BNomad/Model/Place.swift
- BNomad/View/PlaceInfoView/PlaceInfoCell.swift
- #296 
- place 모델에 time을 추가하고 placeInfoModal의 영업시간 데이터를 바인딩 했습니다.
> [Feat] 영업시간 데이터 바인딩

- BNomad/View/PlaceCheckInView/CheckedProfileListHeader.swift
- BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
- #295 
- PlaceCheckInView의 함께 일하고 있는 노마드 목록에서 자신은 제외되도록 작업합니다.
- label text를 수정했습니다. (노마드 → 함께 일하고 있는 n명의 노마드)
> [Feat] #295 PlaceCheckInView 함께 일하고 있는 노마드 목록에서 자기 자신 제외

- BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
- BNomad/View/PlaceInfoView/PlaceInfoCell.swift
- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- BNomad/View/PlaceInfoView/ReviewInfoCell.swift
- BNomad/View/PlaceInfoView/ReviewSubCell/ReviewSubCell.swift
- #298 
- 주소 레이블 잘리던 문제 해결(줄 바꿈)
- 밋업 갯수 리뷰히스토리로 잘못 받아오던 문제 해결
- 유저 위치 정보 없을 때 장소 정보 안받아와서 공란으로 뜨는 문제 해결
- 디바이스가 달라졌을때 셀이 작아보이던 문제 해결
(리뷰 서브 셀과 CheckedProfileListViewCell 의 사이즈를 콜렉션뷰 전체 너비에서 -30으로 사이즈 조정)
> [Bug] PlaceInfoView 버그

- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- BNomad/View/ReviewView/ReviewCell.swift
- BNomad/View/ReviewView/ReviewListViewController.swift
- #282 
- ReviewListView 에 대하여 Data Binding 을 했습니다.
> [Feat] #282 ReviewListView Data Binding

- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- BNomad/View/PlaceInfoView/ReviewInfoCell.swift
- 플레이스 인포 모달 뷰 리뷰 갯수에 따른 사이즈 조정 재추가
- 리뷰 전체보기 버튼 추가
#325
- 플레이스 인포 모달 뷰 리뷰 갯수에 따른 사이즈 조정 재추가
- 리뷰 전체보기 버튼 추가
> [Feat] 모달 사이즈 , 리뷰 전체보기 버튼 추가

- BNomad.xcodeproj/project.pbxproj
- BNomad/API/FirebaseManager.swift
- BNomad/API/FirebaseTestVC.swift
- BNomad/Application/SceneDelegate.swift
- BNomad/View/LoginView/LoginViewController.swift
- BNomad/View/MapView/MapViewController.swift
- BNomad/View/MapView/RegionSelectViewController.swift
- BNomad/View/MeetUpView/NewMeetUpViewController.swift
- BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- BNomad/View/PlaceInfoView/ReviewInfoCell.swift
- BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
- BNomad/View/ReviewView/ReviewDetailViewController.swift
- BNomad/View/ReviewView/ReviewListViewController.swift
- 42개의 warning을 제거했습니다.
- 타입을 명시적으로 변경했습니다. ( as 사용)
- pbx 파일에 중복된 부분을 제거했습니다.
- deprecated된 기능을 수정했습니다.
- [CLLocationManager](https://stackoverflow.com/questions/64073811/authorizationstatus-for-cllocationmanager-is-deprecated-on-ios-14)
- <img width="857" alt="image" src="https://user-images.githubusercontent.com/59302419/203892596-192a5045-6978-45e6-9fa1-8ca5657a85f4.png">
- [UIApplication.shared.windows](https://m.blog.naver.com/tnsqo1126/222796048817)
- <img width="851" alt="image" src="https://user-images.githubusercontent.com/59302419/203892538-61bfb72b-28d1-4b68-8e36-83c0dc6534ac.png">
> [BUG] warning을 제거했습니다.

- BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
- #340
- 모달 사이즈 미디움, 라지로 일괄 수정하였습니다. 비어보이는 공간은 다른 컨텐츠가 들어가거나 들어가지 않은 상태에서도 약간의 수정을 통해 커버하기로 팀의 합의가 있었습니다.
> [Bug] #340 Detent 사이즈 일괄 수정
