BNomad.xcodeproj/project.pbxproj
BNomad/View/MapView/MapViewController.swift

- #7 
- 지도 안에 시장, 학원, 학교 등 다양한 정보가 다 뜨는 것이 지저분해서 공항, 교통, 해변, 캠핑장 등 일부 정보만 남겼습니다. 애플 맵 카테고리 중 선택할 수 있으니 어떤 카테고리들을 맵에 같이 보여줄지 함께 정하면 좋겠습니다.
- 현재 위치로 가는 버튼은 잘 작동하나 나침반 회전 상태에서 현재 위치로 갈 때 회전이 초기화되지 않습니다. 이 부분 추후 해결할 예정입니다.
- 현재 위치 중심으로 원형 overlay 도 잘 구현되지 않아 추후 보완하겠습니다.
- 버튼들은 UI 만 만들어놓았고 액션은 다른 뷰가 구현된 뒤에 연결할 예정입니다.
- 맵을 시작할 때 setRegion이 없으면 대한민국 전도부터 시작을 해서 setRegion을 통해 현재 위치 중심으로 시작하게 바꾸었습니다. 그런데 span 값으로 현재 위치 중심에서 줌인/아웃 정도까지 조절할 수 있는 것으로 알고 있는데, span 값을 달리 줘도 시작하는 화면에 변화가 없습니다. 이 부분이 궁금합니다.
- user tracking 버튼을 눌러 현재 위치로 갈 때 나침반 초기화까지 같이 하는 게 자연스럽다고 생각했는데 네이버 지도를 보니 나침반과 위치를 별개로 동작하게 하긴 하네요. 뭐가 좋을지 의견들이 궁금합니다.
- overlay 그리는 것은 결국 custom annotation 그리는 것과 같은 맥락이라서 다음 이슈에서 pin 들을 그려넣을 때 같이 해결하겠습니다.

[Feat] 맵 기본 화면 구현 완료 (지도, 위치, 기본버튼)

---

BNomad/View/MapView/MapViewController.swift
BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift

- #2
- #46 
- Navigation View 를 통해서 Map 에서 다른 뷰로 이동할때 이전 2번 Issue 에서 했었던 Custom Modal View 가 사라지지 않는 문제점이 발생하였습니다. 또한, 팀원들과 논의한 결과 현재로서는 중요한 기능이 아니라고 판단되어서 애플에서 제공하는 SheetPresentationController 로 대체하였습니다.
- Sheet View 가 중간까지만 펴질 수 있게 detent 를 .medium() 만 설정하였습니다.
- Modal View 를 올리는 버튼을 Map 에서 정확히 어느 부분에 위치시켜야 할 지 고민해봐야 할 것 같습니다.
- Modal View 에서의 Grabber 를 애플에서 자체적으로 제공하는 Grabber 로 통일해야 할지, 아니면 디자인대로 Custom Grabber 를 보여줘야 할지 고민해봐야 할 것 같습니다.

[Feat] #46 NewPlaceViewBeforeCheckIn UI

---

BNomad.xcodeproj/project.pbxproj
BNomad/Utils/Extensions/UIViewController+Extension.swift
BNomad/View/SignUpView/SignUpViewController.swift

- #63 
- `setUser()`를 사용하여 회원가입 시 입력하는 정보를 firebase에 저장합니다.
- `textField` 입력 글자 수 제한 및 카운터가 추가되었습니다. (ProfileEditView 참고함)
- 화면 빈 곳을 터치하면 키보드가 내려가는 UIViewController extension 추가하였습니다.
- (추가) 확인 버튼을 누르면 다음 칸으로 자동 포커스되도록 하였습니다.
- `setUser()` 함수에 넣을 닉네임, 직업, 소개글을 3중 if let으로 unwrapping했는데 이렇게 해도 될까요..
- 이제 뭐하죠
- [화면 터치 시 키보드 내리기](https://open95.tistory.com/4)

[Feat] #63 SignUpView 글자수 제한 추가, 입력값 firebase 저장

---

BNomad.xcodeproj/project.pbxproj
BNomad/API/FirebaseManager.swift
BNomad/Application/CombineViewModel.swift
BNomad/Application/SceneDelegate.swift
BNomad/Application/ViewController.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
BNomad/View/SignUpView/SignUpViewController.swift

#70 
- 유저 로그인 판단 방법을 변경합니다.
- 기존 방식 : userDefaults에 userUid가 존재하는지 유무
- 새로운 방식 : firebase에 userUid 데이터가 존재하는지 유무
- 변경이유 : userDefaults를 초기화하려면 앱을 삭제해야하기 떄문에 번거로워서
- ViewController를 entry point로 변경합니다.
- ViewController의 기능
- 로그인 유무 판단
- 유저 데이터, 유저 체크인 히스토리 데이터 가져오기
- viewModel을 생성합니다
- 여러 viewController에서 가져다 사용할 수 있도록 user, place, login 같은 데이터를 관리
- login 유무에 따라 체크인 버튼을 눌렀을 때 보여지는 view 분기 시키기

[Feat] 로그인 판단 & 체크인 view 분기 & user 데이터 가져오기

---

BNomad/View/MapView/MapData.swift
BNomad/View/MapView/MapViewController.swift
BNomad/View/PlaceInfoView/BasicInfoCell.swift
BNomad/View/PlaceInfoView/PlaceInfoCell.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift

- #66 
- Firebase fetch 로 장소 데이터 다운로드 (비동기)
- 장소핀 구현
- 장소핀 데이터 (이름, 전화번호, 주소 등) 장소 데이터로부터 자동 전달 (PlaceUid 비교 후 Place 자체를 다른 뷰로 전달)
- 장소 모달과 모달을 구성하는 PlaceInfoCell, BasicInfoCell에 place 기반으로 정보 업데이트하는 func 구현
- 자동으로 데이터 들어가는 걸 보니 UI 수정이 또 필요한 게 보이네요 ㅎㅎ
- 특정 annotation을 클릭할 때 span값이 고정상태여서인지 어색하게 줌아웃이 되면서 모달이 뜨는 경우가 있고, 클러스터 상태로 돌아가서 모달만 보일 때도 있습니다. (아래 그림 중 박태준 학술정보관) MVP에서 수정이 필요할지 의견이 궁금합니다.

[Feat] Firebase 장소데이터 연결 및 뷰 간 데이터 전달 구현

---

BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift

- #122 
- hour 변수 값이 0인 경우 "0시간" 이 뜨지 않게 하기 위해 calculateAverageTime 함수 조정.

[Fix] #122 평균 근무 시간이 1시간 이내일 경우 0시간 몇분으로 뜨는 것을 막기 위해 calculateAverageTime 함수 조정

---

BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift

- #122 
- 평균 근무 시간이 1시간 66분, 1시간 0분 등으로 뜨는 현상을 방지하기 위해 modulus 와 if-else 문을 활용하여 calculateAverageTime 함수를 조정했습니다.

[Fix] #126 평균 근무 시간이 이상하게 뜨는 것을 방지하기 위해 calculateAverageTime 함수 조정

---

BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift

- #120 
- UILabel 글자수 길어질 때 튀어나가지 않도록 함
- 나중에 다이나믹하게 레이아웃이 조정되도록 해보고 싶습니다..

[Fix] #120 UILabel 글자수 길어질 때 튀어나가지 않도록 함

---

BNomad/View/ProfileView/ProfileGraphCell.swift
BNomad/View/ProfileView/VisitingInfoCell.swift

- profile 뷰에 장소 이름 viewModel과 연결했습니다.

[fix] profile 뷰에 장소 이름 viewModel과 연결

---

BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
BNomad/View/ProfileView/ProfileViewController.swift

- 
- 이름, 직책 -> 닉네임, 직업으로 수정
- 자개소개 내용 입력칸 글자크기 키움
- 빈 화면 터치 시 키보드 내리기
- 네비게이션바 색상 nomadBlue로 수정
- 프로필수정 취소 버튼 문구 "Back" -> "취소"
- 

[Fix] 프로필뷰 및 프로필수정뷰 사소한 수정

---

BNomad/View/ProfileView/CalendarViewController.swift
BNomad/View/ProfileView/ProfileViewController.swift
BNomad/View/ProfileView/VisitingInfoCell.swift

- 비짓인포셀을 공유하는 두 뷰컨에 대해 다른 nameLable을 반환하도록 수정했습니다
- 텍스트에서 쉐브론 이미지로 버튼을 교체했습니다

[Fix] 프로필뷰, 캘린더뷰 비짓카드셀 분기 설정 / 쉐브론 설정

---

BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift

- 회원가입하지 않으면 체크아웃 뜨는 버그를 수정했습니다.

[Fix] 회원가입하지 않으면 체크아웃 뜨는 버그 수정

---

BNomad/View/ProfileView/CalendarViewController.swift
BNomad/View/ProfileView/ProfileGraphCell.swift
BNomad/View/ProfileView/ProfileViewController.swift
BNomad/View/ProfileView/SelfUserInfoCell.swift

- 프로필뷰와 캘린더뷰의 각 셀 오토레이아웃을 수정했습니다.
- 뷰는 패딩값으로 설정하여 폭을 일정하게 하고, 기존 하드코딩되어있던 각 셀과 내부 요소들의 레이아웃을 뷰에 맞춰 수정함

[Fix] 프로필뷰, 캘린더뷰 오토레이아웃 수정

---

BNomad/Application/CombineViewModel.swift
BNomad/View/MapView/MapViewController.swift

- #97 
- 체크인 후 앱을 껐다 켰을 때 체크인 한 장소로 맵 시작위치 설정
- 해당 장소의 하프모달까지 자동으로 띄움
- 체크아웃 상태에서 디바이스 위치를 받을 때와 못 받을 때 (사용자가 위치 허용 안했을 때) 케이스 분기하여 시작위치 따로 설정
- 데이터 바인딩의 방식 문제로 고민하면서 combine적용을 시도하던 중 Firebase의 place 정보들 fetch가 미처 다 끝나기 전에 맵을 그리려 해서 타이밍이 안맞았다는 걸 발견했고, Firebase의 FetchPlaceAll func 안에 체크인 한 장소 매핑하는 func를 추가해서 해결했습니다.
- combine 적용을 해보려고 combine view model에 체크인 장소를 publisher로 등록한 상태이지만 추후 쓸 일이 없다면 다시 삭제하겠습니다.

[Feat] 체크인 상태에서 앱 새로 시작 시 맵 위치 초기화, 모달표시 기능 구현

---

BNomad/View/MapView/MapViewController.swift
BNomad/View/SignUpView/SignUpViewController.swift

- #152 
- 비 로그인 상태에서도 위치 정보 허용 시 Region 초기화
- extension func MKAnnotationView로 변경 후 데이터 바인딩 수정
- 장소 annotation 이 아닌 클러스터 annotation 클릭 시 자동으로 해당 클러스터 중심으로 확대하여 장소 핀 볼 수 있도록 수정 (thanks to 성수)
- 회원가입 뷰에서 키보드의 return키 입력 시 자동으로 다음칸으로 넘어가게 (확인 버튼과 같은 기능)
- 위치정보 허용, 비허용, 한 번만 허용 케이스를 시뮬레이터로 시험해보니 생각 못했던 에러 메시지들이 많이 나왔습니다. 추후 테스트할 때 기기별로 나눠서 상세하게 봐야할 것 같아요.
- MKAnnotation 만 클릭하는 걸 iOS16 부터 새로 제공하는 이유를 상세하게 찾아봐야 할 것 같습니다. 아직은 숨은 의도를 모르겠네요.
- Will the Code Master 성수 도움으로 클러스터 핀 클릭할 때의 인터랙션이 굉장히 좋아졌습니다. Yo ma sunshiningsoo
- 회원가입 뷰.. 키보드로 쓰다가 위에 확인 버튼 누르는 것도 귀찮을 때 오른쪽 return 키를 누를 수도 있을 것 같아 한 줄만 추가했습니다. (저는 블투 키보드로 연결해서 앱들 쓸 때 return키 안 먹으면 불편했던 기억이 있어서 고쳤습니다 ㅋㅋ)

[Bug] iOS15 이하 버전 Annotation 노출 + 회원가입 텍스트필드 키보드return 구현

---

BNomad/View/MapView/MapViewController.swift

- #152 
- #153 
- '업무중' 모달 클릭 가능
- '업무중' user상태로 실시간 반영
- '업무중' 모달이 안뜨는 이유가 이미 mapviewcontroller 위에 모달이 떠 있어서 안뜨는 것이었습니다
- '영업중'을 누르게 되면 바로 모달들이 dismiss된 이후에 리스트뷰가 올라오게 됩니다.

[Bug] '업무중' 실시간 반영, 클릭가능하게

---

BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift

- #161 
- 코드정리와 함께, CheckInListView의 header UI 작업을 했습니다.
- compositional layout으로 변경하지 않고, 기존의 틀을 가져가기로 했습니다. 이유로는 짧은 기간에 방대한 작업량이 우려되었음...
- 백그라운드의 색상이 아직 적용되지 않았는데, 추후에 CustomColor extension에 값 들어오면 고치려 합니다.
- 상단에서부터, 체크아웃하기 버튼이 있는 곳까지의 UI 작업을 했습니다. 하단은 아직 작업되지 않았습니다.
- 체크인 시간부터 현재 일한 시간만큼의 가로 그래프가 차는데에, 생각해볼 로직이 더 많아 보입니다. (그런데 지금 꼭 해야하는지는 또 미지수,,ㅋㅋ)
- 체크인 가능시간 체크하는 로직이 추가되어야 함
- 체크아웃 시간이 지났을때 자동 체크아웃이 되어야하는 로직
- 장소 데이터에 영업시간이 들어가야함 등등,,,
- stackView사용 https://hyunndyblog.tistory.com/148

[Feat] #161 CheckInListView header UI, 코드정리

---

BNomad.xcodeproj/project.pbxproj
BNomad/Application/SceneDelegate.swift
BNomad/View/MeetUpView/NewMeetUpViewController.swift

- #166 
- 새로운 퀘스트를 생성하는 뷰의 UI 작업입니다.
- 제목, 장소는 15자까지로 제한했습니다.
- 모임 시간은 datePicker로 10분 단위로 선택하도록 했습니다. 처음에는 현재 시간과 가까운 시간이 표시됩니다.
- 모집인원 + - 누르면 숫자가 바뀌도록 했습니다. 2명 이하로는 내려가지 않도록 했습니다.
- 모집인원 + - 버튼을 스택뷰로 만들었는데 가운데 divider가 완전히 한가운데가 안되네요..
- DatePicker (https://formestory.tistory.com/6, https://zeddios.tistory.com/291)
- textView placeholder (https://hyongdoc.tistory.com/280)

[Feat] #166 NewMeetUpView UI 작업 완료

---

BNomad.xcodeproj/project.pbxproj
BNomad/Model/Place.swift
BNomad/View/MapView/MapData.swift
BNomad/View/MapView/MapViewController.swift
BNomad/View/MapView/RegionCollectionViewCell.swift
BNomad/View/MapView/RegionSelectViewController.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift

- #165 
- 임시로 4개 지역 선정하여 맵 이동 (선택 후 확인 버튼)
- 지역 선정 모달 구현 (컬렉션뷰, 셀)
- 맵 신규 UI에 맞춰 버튼 위치 이동, 스택뷰 수정
- 지역 정보 커스텀 모델, 데이터 구축
- 체크인 상태에서 자신이 체크인한 장소를 기준으로 맵을 원복시키는 기능을 기존에 넣어놨는데, 지역 이동하고 여러 코워킹스페이스를 구경하다보니 계속 체크인 장소로 돌아가는게 불편하게 느껴져서 규칙을 수정해야 할 것 같기도 합니다.
- 예: 다른 지역을 보다가 업무중 버튼을 눌러서 모달을 보고 나오면 타 지역 그대로 유지가 안되고 코워킹스페이스 중심으로 맵 원복
- 전국 단위에서 핀 클러스터가 보이다보니 클러스터를 눌러도 충분하게 확대가 안되네요. 이전에 얘기했던대로 일정 축척 이상으로 지도를 넓게 보면 핀 annotation 대신 지역명을 눌러서 지역 단위로 먼저 확대를 시켜줘야 할 것 같기도 합니다. 그 뒤에 핀을 띄우는 방식으로...
- 마찬가지로 전국을 보다가 쉽게 남한이 아닌 북한, 일본, 중국으로 넘어갈 수 있는 걸 막아야 할 것 같습니다.
- 현재 핀 정보를 firebase에 정리해 넣듯이 지역 정보도 신규등록, 저장, 관리하기 좋은 방식이 있을 것 같은데 조언 부탁드립니다. 다만 지역은 코워킹 스페이스만큼 종류가 많지 않고 한 번 세팅하면 수정도 많지는 않을 것 같아서 현재는 RegionData 로 써넣었습니다.

[Feat] 지역 선택 기능 구현 및 신규 UI 변경

---

BNomad/View/SignUpView/SignUpViewController.swift

- #178 
- 단계 이동시 누르는 버튼 디자인을 수정했습니다. 단계 이동시 "다음", 전체 완료 시 "확인"으로 타이틀이 바뀝니다.
- 상태 입력칸을 자기소개(textView)로 수정하고 150자 제한을 반영했습니다.
- 4번째 입력 단계(프로필 사진 등록)를 추가했습니다.
- 4번째 단계 추가에 따라 상단 문구 수정, 우측상단 점 등 수정했습니다.
- 자기소개(textView) 입력 시에도 키보드 악세서리로 다음 버튼이 나오게 하고 싶은데 안나오네요.. 근데 일단 키보드와 다음 버튼이 자기소개 칸을 
가릴까봐 그냥 이대로 두었습니다. 
- 피그마 디자인과 프로필 사진 선택 버튼 위치가 다른데, 윌로우가 디자인 변경해도 된다고 했기도 하고 아래와 같은 사유로 지금처럼 작업했습니다.
- 1) 다음 누를때마다 아래에 칸이 추가되다가 갑자기 위에서 나타나면 이상할 것 같음
- 2) textField들이 화면 하단으로 내려가는 경우 스크롤이 안되는 현재 상황에서 키보드가 입력칸들을 가리게 됨
*자기소개 입력 시 키보드 올라오면 가려지므로 뷰 올라가도록 수정(11/10 오전)
- [키보드가 textView를 가릴 때 뷰 올리기](https://medium.com/swiftcommmunity/swift-keyboard-control-of-textfields-and-textviews-c20112528392)

[Feat] #178 SignUpView 수정

---

BNomad/View/MapView/MapViewController.swift
BNomad/View/MapView/RegionCollectionViewCell.swift
BNomad/View/MapView/RegionSelectViewController.swift

- #165 
- 텍스트까지 버튼으로 묶음
- 다른 모달 뜬 상태에서 지역버튼 클릭 가능
- 텍스트 스타일 수정
- '지역 선택' 텍스트를 chevron.down 과 함께 묶어 버튼 처리를 했더니 폰트 스타일 적용이 제대로 안되는 것 같습니다. asFont func도 안되고... 좀 더 알아보겠습니다.

[Bug] 지역선택 버튼 버그 수정

---

BNomad/View/MapView/MapViewController.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift

- #188 
- 비로그인 상태에서 1) 프로필 버튼, 2) 체크인 버튼 누를 때 로그인 하시겠냐는 alert 을 만들어 띄웁니다.
- 로그인 하겠다고 누르면 로그인뷰로 이동시킵니다. (현재는 회원가입 뷰로 이동)
- 프로필 보기, 체크인 하기 외에도 로그인이 필요한 action이 있을지 더 고민해봐야 합니다. (예: 설정 뷰 안에서 회원 관련 메뉴들...?)

[Feat] 비로그인 상태에서 로그인 뷰로 넘어가는 alert 구현

---

BNomad/View/ProfileView/CalendarViewController.swift
BNomad/View/ProfileView/ProfileGraphCell.swift
BNomad/View/ProfileView/ProfileViewController.swift
BNomad/View/ProfileView/SelfUserInfoCell.swift
BNomad/View/ProfileView/VisitingInfoCell.swift

- #197 
- 캘린더뷰로 넘어가는 버튼을 상단 네비게이션 아이콘에서 뷰 안의 카드로 전환하였습니다
- 비짓카드 리스트 뷰를 구현했습니다
: 현재 헤더와 섹션 없이 모든 카드가 일렬로 있는 상태입니다, 수정 필요함
- 캘린더뷰에서 빨간 사각 버튼을 누르면 전환됩니다

[Feat]캘린더 비짓카드뷰 구현 및 네비게이션 루트 변경

---

BNomad/View/MapView/MapViewController.swift

- #199 
- 자기 자신의 핀은 클릭되지 않도록 막았습니다.
- 리스트보기 버튼과 본인 위치로 가는 버튼의 디자인을 사각형으로 만들어서 user tracking 모드의 버튼과 디자인 통일성을 맞췄습니다.
- 리스트보기 모달은 large로 변경했다가 다시 medium으로 유지시켰습니다. (리스트 안의 장소를 클릭했을 때 모달 두개가 겹쳐 UI 불편)
- 나침반 위치를 수정했습니다.
- 시도때도 없이 체크인위치나 본인 위치로 맵이 리셋되던 것을 막고, 앱을 구동할 때만 리셋하도록 수정했습니다.
- 다른 지역을 탐색하다가 업무중 버튼을 누르면 체크인한 장소의 체크인뷰 모달이 떴다가 사라지는데, 맵은 여전히 다른 지역 모습 그대로인게 좀 어색하더라고요. 업무중 버튼에 scope 모양을 추가해서 저걸 누르면 map도 이동하고 모달도 뜨는 방식은 어떨까요?

[Fix] 맵 버그 수정 완료

---

BNomad.xcodeproj/project.pbxproj
BNomad/View/MapView/MapViewController.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift

- #202 
- 맵뷰 delegate 중 mapViewDidChangeVisibleRegion 메소드를 사용해서 지도에서 보는 영역을 바꿀 때마다 함수를 실행하게 했습니다.
- 맵 안에 보이는 영역 (mapView.visibleMapRect) 과 핀을 표시하는 포인트 (MKMapPoint) 를 비교해서 포인트가 영역 안에 포함되는지 판별하게 했습니다.
- 판별 후 영역 안에 있는 핀 -> 장소 정보는 visiblePlacesOnMap 이라는 커스텀 배열 안에 추가하고, 영역 안에서 사라지는 장소는 배열에서 뺍니다.
- 테스트 결과 작동은 합니다만, 정확도가 높지는 않습니다 ㅠㅠ 정확도를 높이기 위한 추가 작업을 할 예정입니다.
- 지도를 아주 조금만 움직여도 굉장히 많은 횟수로 영역 내 있는지 없는지 체크를 하는 걸 콘솔을 통해 볼 수 있었습니다. 나중에 앱 속도 저하 문제가 생기거나 하지는 않을지 걱정이 되네요.
- 정확도 문제가 2가지 부분에서 생기는 것 같습니다. 계속 개선할 예정인데 조언 부탁드립니다.
- 맵 영역이 우리가 폰으로 보는 영역과 미세하게 다를 경우, 화면에는 핀이 약간 보이는데 앱은 영역 밖으로 나갔다고 인식
- 영역 내 핀 포함여부를 제대로 인식하더라도 리스트에 바로 바인딩해주는 게 시차가 생기는 문제
- https://developer.apple.com/documentation/mapkit/mkmapviewdelegate/2998428-mapviewdidchangevisibleregion
- …

[Fix] 맵 안에 보이는 장소들만 골라서 리스트에 보내주기

---

BNomad.xcodeproj/project.pbxproj
BNomad/View/PlaceInfoView/PlaceInfoCell.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
BNomad/View/PlaceInfoView/ReviewInfoCell.swift
BNomad/View/PlaceInfoView/WithNomadCell/WithNomadHeader.swift

- #208
- PlaceinfoModalViewController내 컬렉션뷰에 섹션 추가
- Header를 새로운 셀로 분리하여 데이터 바인딩, 텍스트 변경
-Will이 구현한 CheckedProfileListHeader 변경
-CheckedProfileListViewCell 3번 섹션에 적용

[Feat] #208 3번째셀 구현

---

BNomad/View/ProfileView/CalendarViewController.swift
BNomad/View/ProfileView/ProfileGraphCell.swift
BNomad/View/ProfileView/ProfileGraphCollectionCell.swift
BNomad/View/ProfileView/ProfileViewController.swift
BNomad/View/ProfileView/VisitingInfoCell.swift

- #205 
- 캘린더뷰에서 날짜 클릭 시 비짓카드가 하나만 생성되던 것을 체크인 갯수에 맞추어 여러개 생성될 수 있게 반응형 수정함
- 캘린더뷰컨트롤러, 캘린더뷰셀, 비짓카드셀 파일에 대해 상기 기능 구현에 관련된 로직 리펙토링 진행
- 프로필뷰의 통계 부분의 시간간격을 3시간으로 수정 (논의필요)
- 시간이 짧으면 보이지 않았던 문제 해결

[Fix] 캘린더뷰 비짓카드 다중생성 및 코드 리펙토링

---

BNomad/Utils/Extensions/UIColor+Extension.swift
BNomad/View/MapView/MapViewController.swift
BNomad/View/MeetUpView/MeetUpViewController.swift
BNomad/View/MeetUpView/NewMeetUpViewController.swift
BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
BNomad/View/PlaceCheckInView/QuestCollectionViewCell.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift

- #189 
- 체크인뷰에서 + 버튼 누르면 NewMeetUpView가 뜨도록 했습니다.
- TempMeetUp(모델), TempMeetUpData(임시데이터)를 만들어 퀘스트셀을 그리고 셀 하나를 탭하면 그 데이터로 MeetUpView를 그리도록 했습니다.
- MeetUpView는 체크인뷰 모달 내에서 네비게이션으로 이동되도록 했습니다.
- PlaceCheckInView UI를 피그마에 맞춰 일부 수정했습니다.
- MeetUp모델이 있는데 TempMeetUp를 만들어서 한 것은 각종 id값들을 임의로 넣기 어려워서.. 일단 단순히 콜렉션뷰셀 내 콜렉션뷰셀 탭했을 때 데이터를 가지고 상세뷰로 이동하는 것을 구현하기 위함이었습니다. 추후 데이터 연결 시 바꾸어야 합니다.
- [TableViewCell 내 CollectionViewCell 탭하여 present/pushViewController 동작](https://www.youtube.com/watch?v=KCgYDCKqato)
- [모달 내 네비게이션 동작](https://stackoverflow.com/questions/56435510/presenting-modal-in-ios-13-fullscreen/58255416#58255416)
- [네비게이션 있는 모달 풀스크린으로 만들기](https://stackoverflow.com/questions/56435510/presenting-modal-in-ios-13-fullscreen/58255416#58255416)

[Feat] #189 체크인뷰와 밋업뷰, 밋업생성뷰 연결

---

BNomad/View/LoginView/LoginViewController.swift

- #210 
- 기존 LoginViewController에서 UI를 업데이트해서 작업했습니다.
- LoginViewController의 기본 액션과 UI만 작성을 했기에, 뷰가 이어져 있지는 않습니다.
- @limhyoseok  apple login을 한뒤에 `SignUpViewController`로 이동하게 되는데, `SignUpViewController`를 꺼버리면, `LoginViewController`의 `authorizationController`에서 이미 FirebaseAuth에는 apple login이 완료되었다 생각해 정보가 올라가게 되지만, `SignUpViewController`에서 닉네임등을 다 작성해야 Firestore에 User 데이터가 올라가게되어 Auth와 Firestore가 일치하지 않는 문제가 있을 것 같습니다. 어떻게하면 좋을까요?
피그마와 동일해, 하프모달에서 문제 없어 보입니다.

[Feat] #210 애플로그인모달 UI완성

---

BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift

- 피그마에 맞춰 자잘한 UI 수정
- 체크인, 이용시간 프로그래스바 구현
- 0시부터 24시까지의 timeBar 위에 체크인 시간부터 이용시간(현재시간)까지 nomadBlue 컬러로 하이라이트 하였습니다.
- timeBar 길이와 하루 길이(1440분)에 대한 비례식을 이용해서 checkInTimeBar의 좌우 padding이 달라지도록 했습니다.
- 피그마에 맞추어 자잘한 UI 수정했습니다.
- 프로그래스바가 `checkIn`의 `didSet` 안에서 그려지도록 했는데 더 좋은 방법이 있을지 모르겠습니다. configUI() 등 여러 위치에서 해봤는데 필요한 값(checkInTimeInMinutes)을 따로 변수로 만들어서 넣고 가져와도 값이 제대로 안들어가 있습니다..
-

[Feat] #226 PlaceCheckInView 체크인, 이용시간 프로그레스바 구현

---

BNomad.xcodeproj/project.pbxproj
BNomad/View/ProfileView/CalendarViewController.swift
BNomad/View/ProfileView/ProfileGraphCell.swift
BNomad/View/ProfileView/ProfileViewController.swift
BNomad/View/ProfileView/VisitCardCollectionViewController.swift
BNomad/View/ProfileView/VisitCardHeaderCollectionView.swift

- 기존 profileCollectionView 위에 얹혀있던 profileGraphCollectionView를 프로필뷰컨 -> 프로필컬렉션뷰셀으로 이동하여 한 묶음으로 처리하는 리펙터링 진행
- 이외 자잘한 리펙터링
- 비짓카드컬렉션뷰 헤더 생성 (현재 모든 셀에 대해 날자 헤더가 생성됨, 추후 월별/주별 등 분리 필요)
- static을 너무 많이 쓴 것 같습니다 특히 프로필그래프셀 내에서

[Feat] 프로필뷰 리펙터링(그래프 뷰컨->셀 이동) 및 비짓카드컬렉션뷰 헤더 생성

---

BNomad/View/PlaceInfoView/PlaceInfoCell.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
BNomad/View/PlaceInfoView/ReviewInfoCell.swift
BNomad/View/PlaceInfoView/ReviewSubCell/ReviewSubCell.swift

- (#233)
- 영업중 레이블 삭제
- 영업시간 정보 표기 방법 변경
- 확장버튼(쉐브론) 및 기능 삭제
- 셀 간격 조정

[Feat] 영업중 섹션 UI디자인 변경 적용

---

BNomad.xcodeproj/project.pbxproj
BNomad/Application/SceneDelegate.swift
BNomad/BNomad.entitlements
BNomad/View/LoginView/LoginViewController.swift
BNomad/View/MapView/MapViewController.swift
BNomad/View/PlaceInfoView/PlaceInfoCell.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
BNomad/View/SettingView/SettingViewController.swift
BNomad/View/SettingView/WithdrawViewController.swift
BNomad/View/SignUpView/SignUpViewController.swift

- #224 
- 애플로그인을 Firebase와 연결했습니다.(회원가입 + 로그인)
- 로그아웃을 만들었습니다.
- 회원 탈퇴를 만들었습니다.
- user가 nil일때의 PlaceInfoModal UI를 수정했습니다.
- FirebaseAuth에 맞게 Scenedelegate를 수정했습니다.
- FirebaseAuth 재설정한 것들이 project파일에 순서 변화를 준 것 같습니다.
- GoogleService-info.plist 변경이 있어, 머지된 이후에 팀원 전부가 설정해야 할 것이 있습니다.
- 유저의 상태가 기존상태에서 늘었습니다. (회원가입O, 회원가입X) -> (로그인+회원가입O, 로그인+회원가입X, 로그인된 유저X)
- 애플로그인 보안토큰 생성을 위해 Firebase, Apple example code를 사용했습니다
- 이 PR이 머지된 이후로는, 회원가입을 애플로그인을 통해서만 진행하기 때문에, 시뮬레이터에서 테스트하지 못하는 경우가 있습니다.
- 추가로 설정해야할 파일이 `team provisioning파일설정`과 `팀인증서 등록`이 있기 때문에, 저에게 파일을 요청하면 됩니다!👍(직접 해드림!)
- 아마 로그인 로그아웃 상태에서의 빈 로직이 있을 것 같은데 같이 찾아보면 좋을 것 같습니다👨‍💻
- [애플로그인](https://www.kyulabs.app/3813c4d9-8343-40c6-a02c-26ccfa7e2731)
- [firebaseAuth + 애플로그인](https://huree-can-do-it.notion.site/Firebase-Apple-Login-dbabbe8d59a04d …

[Feat] #224 애플로그인, UI작동, 로그인, 로그아웃, 회원탈퇴

---

BNomad/View/SignUpView/SignUpViewController.swift

- #236 
- 닉네임, 직업, 자기소개 작성 후 다음 버튼을 누르면 세 가지의 입력칸들이 사라지고 사진 업로드 버튼이 나타납니다.
- 가입 중 상단의 취소 버튼을 누르면 계속 작성/작성 취소 alert가 뜹니다.
- 모두 완료하고 확인 버튼을 누르면 회원가입이 완료되었다는 alert가 뜨고 맵뷰로 돌아갑니다.
- 입력단계별 다음/확인 버튼의 액션을 작성하는 코드가 복잡하여 우선 주석으로 각 단계를 표시해 놓았는데, 추후 enum과 별도 함수로 나눠서 stage별로 필요한 함수가 실행되도록 리팩토링해볼 생각입니다...
<p list="left">
</p>

[Enhancement] #236 SignUpView 업데이트

---

BNomad/View/MapView/MapData.swift
BNomad/View/MapView/MapViewController.swift
BNomad/View/MapView/PlaceAnnotation.swift

- #230 
- 스위치 on/off 시에 기존의 맵 annotation 모두 삭제한 뒤 방문했던 장소만 추가하거나 모든 장소 추가하는 방식으로 구현
- 토글을 누른 순간에만 체크인 히스토리 중에 방문한 장소를 골라내어 지도에 표시
- 임시로 토글로 구현했는데 어울리는 디자인이 나오면 변경 예정입니다.
- 방문했던 장소만 보는 토글 상태일 때 좌측 하단의 장소 리스트 누르면 비방문 장소까지 다 나오는 상황입니다. 이 부분 UI 상 어색하지 않을지 의견부탁드립니다.
- 스크린샷에는 실시간으로 체크인, 체크아웃 하는 장소는 토글에 반영이 되지 않지만 스크린샷 캡쳐 후에 다시 수정해서 앱을 껐다 켜지 않아도 체크아웃한 장소는 토글에 정상 반영됩니다.

[Feat] 방문했던 장소만 모아보는 토글 구현 완료

---

BNomad/API/FirebaseManager.swift
BNomad/View/MeetUpView/MeetUpViewController.swift
BNomad/View/MeetUpView/ParticipantCell.swift
BNomad/View/PlaceCheckInView/QuestCollectionViewCell.swift

- #246 
- 체크인뷰에 보이는 밋업셀에는 협의된 것과 같이 작성자의 프로필이미지만 보이도록 했습니다.
- 밋업셀, 밋업 상세뷰의 프로필 이미지가 동그라미로 나오도록 했습니다.
- 참여중인 밋업의 경우 밋업상세뷰에서 참여하기 대신 참여 취소 버튼이 나오도록 했습니다.
- (수정) 참여 취소 버튼을 누르면 확인 alert이 나오고 확인을 누르면 참여가 취소됩니다.
- ~~참여 취소가 되도록 구현하고 싶었는데 FirebaseManager에 참여 취소 함수가 별도로 없습니다.~~
- ~~참여할 때 participateMeetUp() 함수를 불러와 currentPeopleUids에 userUid를 .append시키길래.. 참여 취소는 같은 함수에 remove를 넣어보았는데 제대로 동작하지 않는 것 같습니다(아래 그림). 작성자가 참여 취소해서 그런걸까요..? participateMeetUp()을 이용하면 안되는 걸까요? @limhyoseok~~ → (수정) FirebaseManager에 참여 취소 함수가 추가되어 해결되었습니다!!
<p list="left">
</p>
12시 넘으니까 어제 많던 밋업이랑 참여자가 다 없어졌네요ㅜㅠ
<p list="left">
</p>
<p list="left">
</p>

[Feat] #246 MeetUpView 밋업 프로필사진 둥글게, 참여중인 경우 참여 취소 버튼

---

BNomad/API/FirebaseManager.swift
BNomad/View/MapView/MapViewController.swift
BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
BNomad/View/ReviewView/ReviewDetailViewController.swift

- #250 
- 리뷰 작성 페이지로 넘어갈때, 장소 title을 넘겨줍니다
- 리뷰 작성 완료를 누르면 Firebase로 저장됩니다.
- 이미지 데이터가 있을때와 없을때의 분기 처리를 해주었습니다.
- 로그인 할때도 그렇고, 지금도 그렇고 이미지 업로드에 꽤 많은 시간이 드는 것 같아 다 합치고 spinner 작업을 해주어야 할 것 같습니다.
https://user-images.githubusercontent.com/72736657/202362841-6628d944-351b-4ee7-a2a0-c47830766d37.mov

[Enhancement] #250 리뷰 데이터 바인딩 및 Firebase 업데이트

---

BNomad/Utils/Extensions/UIColor+Extension.swift
BNomad/View/PlaceInfoView/PlaceInfoCell.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
BNomad/View/PlaceInfoView/ReviewInfoCell.swift
BNomad/View/PlaceInfoView/ReviewSubCell/ReviewSubCell.swift
BNomad/View/PlaceInfoView/WithNomadCell/WithNomadHeader.swift

- #258 
- 각 섹션의 ui디자인 변경점 적용과 오토레이웃 세부 조정
- 피그마에 추가된 nomad2Separator 컬러 익스텐션에 추가
- 1번 리뷰 섹션의 높이를 리뷰의 갯수에 따라 높이를 조정 하는 코드를 구현 하려고 했으나
- 리뷰가 없을시 섹션 자체가 안 보이게, 한개 이상일시 (최대 4개로 고정) 400으로 고정 했습니다.
- 리뷰가 1개~3개일 경우에 따라 높이를 적용하는 방법은 더 공부를 해서 적용하겠습니다.

[Feat] PlaceInfoModal View 내에 DynamicHeight 구현 및 UI 세부 조정

---

BNomad/View/ProfileView/ProfileViewController.swift
BNomad/View/ProfileView/SelfUserInfoCell.swift

- 프로필뷰 UI가 피그마와 같아졌습니다
- 프로필컬렉션뷰 리펙터링이 진행되었습니다
- 프로필 오토레이아웃 수정 및 스크롤뷰가 추가되었습니다

[Feat] 프로필뷰 UI수정, 오토레이아웃 및 버그 픽스

---

BNomad/View/MeetUpView/MeetUpViewController.swift
BNomad/View/MeetUpView/NewMeetUpViewController.swift
BNomad/View/MeetUpView/ParticipantCell.swift
BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift

- #231 
- 밋업 작성자에게만 편집 버튼이 보입니다.
- 편집 버튼을 누르면 편집뷰로 넘어가고 제목, 장소, 내용에 빈칸이 있으면 경고문구가 나오도록 했습니다.
- 완료 버튼을 누르면 저장하겠냐는 alert가 뜨고 확인을 누르면 변경 내용이 저장됩니다.
- ~~스크린샷 찍다보니 오거나이저인데도 불구하고 참여하기 버튼으로 나오네요.. 별도로 수정하겠습니다ㅜㅜ~~ → 다른 브랜치는 제대로 나오네요^^.. dev pull 해서 다시 체크하겠습니다...(그래도 안되면 제대로 나오는 브랜치 머지된 후..)

[Feat] #231 밋업 편집 구현

---

BNomad/View/MapView/MapViewController.swift
BNomad/View/MeetUpView/ParticipantCell.swift
BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
BNomad/View/PlaceCheckInView/QuestCollectionViewCell.swift
BNomad/View/ProfileView/ProfileViewController.swift

- #256 
- 노마드 목록에서 한 명을 탭하면 그 사람의 프로필뷰로 넘어가도록 바인딩했습니다.
- 체크인뷰에서 보이는 프로필이미지들을 동그랗게 만들었습니다.
- 프로필뷰가 다시 대대적 수정이 되고있는듯하여 추후 제대로 동작하는지 다시 체크해 보아야 할 듯 합니다.

[Feat] #256 체크인뷰의 노마드들을 클릭하면 각자의 프로필뷰로 이동

---

BNomad/API/FirebaseManager.swift
BNomad/View/MapView/MapViewController.swift
BNomad/View/SettingView/SettingViewController.swift
BNomad/View/SettingView/WithdrawViewController.swift

- #257
- `로그아웃`, `회원탈퇴`시, 현재 체크인 상태라면, 체크아웃으로 바꾸고, 밋업에 참가중이라면 밋업에서 나오게 만든 후, `로그아웃`, `회원탈퇴` 로직이 실행되도록 만들었습니다.
- 기존 `profileView`로 넘어가는 로직이 `viewModel.isLogIn`으로 검사를 했는데, 이를 `유저의 유무`로 바꾸었습니다.
- 유저의 상태가 다양해져서, isLogin으로 커버가 안되었음 (예시: 애플로그인은 되었는데, 회원가입은 안된 상태)
- MapViewController의 viewWillAppear에서 네비게이션 바를 hidden 해서 SettingView를 닫으려다 다시 열면 네비게이션 타이틀이 없어지는 오류가 있었는데, 이를 고쳤습니다.
- FirebaseManager에서 `MeetUp`데이터가 없을때, String값을 던져서 없다는 것을 판단해도 될지요?!
- 현재 코드에 `업무중`인 상태에서 로그아웃을 해버리면, checkInHistory의 모든 데이터를 지워버리는데, 이유가 뭘까요..?
- `업무중`이라면 체크아웃 -> 참여중인 밋업 삭제인 순서로 로직이 진행되는데, 유저의 checkInHistory가 왜 지워질까요..?
- 로그아웃, 회원탈퇴에서 불가피하게 많은 Firebase관련 함수들이 줄지어 있는데, 더 좋은 로직 있으면 알려주세요..
- 지금 줄지어 코드가 확인하는 것은 `1.유저 유무`,` 2. 유저 현재 체크인 유무,` `3. 체크아웃`, `4. 밋업 유무` `5. 밋업 나오기` 순으로 짜여있어서 너무 보기 좀 그런 코드입니다..

[Enhancement] #257 로그아웃, 회원탈퇴 Firebase 업데이트 구현, SettingView 네비게이션 오류 고침

---

BNomad/View/ProfileView/ProfileViewController.swift
BNomad/View/ProfileView/VisitingInfoCell.swift

- 기적적인 스크롤뷰 버그 픽스
- 카드 UI 약간 수정
- 이게 왜 되지? 의 대표격 픽스입니다
- contentView에 아무런 뷰도 add한 적이 없는데, contentView의 오토레이아웃을 지우면 스크롤이 불가합니다. 이유가 무언지 찾지 못했습니다

[FIX] 프로필뷰 스크롤 버그 픽스

---

BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
BNomad/View/ProfileView/ProfileViewController.swift
BNomad/View/ProfileView/VisitingInfoCell.swift
BNomad/View/SignUpView/SignUpViewController.swift

- #275 
- 체크인뷰에서 노마드 목록이 제대로 나오지 않던 문제를 수정했습니다.
- 노마드를 탭하면 프로필뷰에 체크인 히스토리가 나오지 않던 문제를 수정했습니다.
- 다른 노마드 프로필에서 체크인 기록을 보고 나오면 프로필 사진이 뜨지 않습니다.. 그런데 피그마 프로토타입 업데이트에 따라 추후 다른 노마드 프로필 보기는 체크인 기록을 한 depth 더 들어가서 보지 않으므로 일단 여기서 멈추었습니다.
- 버그리포트 중 특정 노마드는 프로필뷰에 데이터가 바인딩되지 않는 문제는 처음 가입하고 한번도 프로필수정 하지 않은 사람에게 발생하는 것 같습니다.. 도움 부탁 드립니다. @limhyoseok @sunshiningsoo 

[Bug] #275 노마드 프로필 데이터 바인딩 수정

---

BNomad.xcodeproj/project.pbxproj
BNomad/View/ProfileView/CalendarViewController.swift
BNomad/View/ProfileView/ProfileHeaderCollectionView.swift
BNomad/View/ProfileView/ProfileViewController.swift
BNomad/View/ProfileView/VisitCardCell.swift
BNomad/View/ProfileView/VisitCardCollectionViewController.swift

- 프로필뷰 UI가 피그마와 같아졌습니다.
- 일부 로직을 수정했습니다.
- 프로필뷰 비짓카드의 체크인&체크아웃 시간의 경우, 아직 체크아웃하지 않았을 때는 현재 시간이 표기되도록 임의로 작성했습니다

[Feat]프로필뷰 UI 수정 및 버그픽스

---

BNomad/View/MapView/MapViewController.swift
BNomad/View/PlaceInfoView/PlaceInfoCell.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift

- #253 , #270 
- 체크인 카드 내 장소, 시간 바인딩 개선 (앱 재시작, 체크인 직후 등 모두 해결)
- 체크인 상태에서 체크인 한 장소 모달을 볼 때 체크아웃 대신 "이 곳에 체크인 중" 버튼 -> 체크인 뷰 모달 진입점
- 버튼 액션 수정

[Fix] 체크인 카드 바인딩 & 체크인 후 장소 모달 내 버튼 변경

---

BNomad/API/FirebaseManager.swift
BNomad/View/SettingView/WithdrawViewController.swift

- #289 
- 탈퇴이유를 건들이지 않고 `placeholder`인 상태로 탈퇴하기를 눌렀을 때, 서버에 `'탈퇴이유를 적어주세요.'`가 안올라게 막아놨습니다.
- 탈퇴시, `storage`에 저장되어 있는 유저 프로필이미지를 삭제합니다.
- 프로필이미지 Storage를 건들일 경우가, `1. 프로필 수정` `2. 탈퇴` 두가지 경우가 있는데, `1. 프로필 수정`은 `UserUid`를 활용해, 바뀌는 이미지를 덮어쓰는 형식이어서, `Storage`에서 이미지 삭제할 경우는, `2. 탈퇴`만 생각해서 `completion handler`를 사용하지 않았습니다.
- 지금 프로필 이미지 등록은 안하고 회원가입을 해도, 기본 UIImage가 storage에 업로드가 되네요..?!
- 탈퇴하는 유저의 프로필 이미지를 삭제했을때, 해당 유저가 리뷰를 남긴 것이 있다면 로드가 안되거나 crash가 날 가능성이 있는 것 같네요..
REF: [Firebase Auth delete](https://firebase.google.com/docs/auth/ios/manage-users)

[Bug, Enhancement] #289 탈퇴이유 default 업로드 막음, 탈퇴시 Storage이미지 삭제

---

BNomad/View/MapView/MapViewController.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift

- #291 
- user의 `position`값을 가져오지 못하면, app crash현상이 일어나는 것을 Fix함
- 기존 position이 안들어오면 return해버리는 코드에서 default값을 주는 것으로 바꿈
- 위치서비스를 활성화하라는 알림을 기존 `1. place annotation 클릭`할때와 `2. custom 모달을 띄울때` 두가지에서, PlaceInfoViewController에서 `체크인 버튼을 누를때`로 변경함
- 기존 locationCheck 함수가 CustomViewController에서 빠지고 PlaceInfoModalViewController에 추가됨
- position값이 전달안되면서 다른 변수값, 예를 들면 place data, 전화번호, 주소 등을 가져오지 못하는 **오류가 있습니다.**
- 위 문제는 뷰 담당하는 분이 추후에 수정 부탁드립니다! @Willowwryu 
- @hardworking-nomad  위치설정이 켜지지 않았을때, 나침반 혹은 자신의 위치로 돌아가는 버튼이 눌렸을때,`locationCheck()` 를 사용해 줘야 할 것 같네요..?! MapViewController에 `locationCheck()` 함수 다시 올려놓겠습니다..!
REF: [위치 활성화 확인](https://0urtrees.tistory.com/19)

[Bug] #291 user position 값으로 app crash되는 현상 Fix

---

BNomad.xcodeproj/project.pbxproj
BNomad/View/PlaceCheckInView/NoMeetUpCell.swift
BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
BNomad/View/PlaceCheckInView/QuestCollectionViewCell.swift

- #293 
- 밋업이 없을 때 표시할 셀을 작업했습니다.
- 버그리스트트의 밋업셀 배경 색상 수정하였습니다. (`nomad2White` → `.white`)
- 피그마의 문구 수정사항 반영했습니다. (`"밋업"` → `"오늘의 밋업"`)
<p list="left">
</p>

[Feat] #293 PlaceCheckInView 밋업 없을 때 표시할 셀 추가

---

BNomad/View/MapView/MapViewController.swift
BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift

- #301 
- userCombine의 checkIn 여부에 따라 업무중 버튼 및 네비게이션바 색상 변경 한 번에 연결
- 장소 리스트 모달 등장 시 맵 작동 안되도록 수정
- 장소 리스트 모달 안에서 하나의 장소 클릭 시 맵 위치 이동
- 체크인 여부에 따라 상단 네비게이션 즉시 변경
- 장소 리스트 모달에서 지도 컨트롤 불가 & 특정 장소 클릭 시 지도 변경

[Bug] 네비게이션바 색상 변경 해결 & 커스텀 모달 버그 해결

---

BNomad/View/ProfileView/CalendarViewController.swift
BNomad/View/ProfileView/ProfileGraphCell.swift
BNomad/View/ProfileView/ProfileGraphCollectionCell.swift
BNomad/View/ProfileView/ProfileHeaderCollectionView.swift
BNomad/View/ProfileView/ProfileViewController.swift
BNomad/View/ProfileView/SelfUserInfoCell.swift
BNomad/View/ProfileView/VisitCardCell.swift
BNomad/View/ProfileView/VisitCardCollectionViewController.swift
BNomad/View/ProfileView/VisitCardHeaderCollectionView.swift

- #316 
- 프로필뷰 UI를 개선했습니다
- 체크하웃하지 않은 상태에서 프로필뷰 진입 시, 비짓카드의 시간을 "체크인시간 ~" 으로 표시되게 수정했습니다 (ex: 17:30 ~)
- 프로필뷰의 통계 섹션에서, 그래프 세로축 시간 범위를 00시~24시로 수정했습니다
- 캘린더뷰의 리스트 보기 모드에서 헤더를 생성했습니다 (현재 모든 셀에 대해 헤더가 생성됨, 같은 날자별로 묶어줘야 함)
- 

[Enhancement] 프로필뷰 UI 개선

---

BNomad/View/SettingView/SettingViewController.swift

- #304
- 유저가 로그인 혹은 로그아웃할 때, 테이블뷰의 리스트명을 토글해줍니다
- 회원탈퇴의 경우에 오른쪽에 chevron.right가 있어서, 디자인상 통일감으로(제 뇌피셜,,) 순서를 바꾸진 않았습니다.. 괜찮을까요?!

[Enhancement] #304 로그인 로그아웃 toggle

---

BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift

- #310 
- customModalcell에서 reuse되는 문제를 fix 합니다
- 파일 rename은 xcode에서 시간이 너무 걸려 추후로 미뤘습니다..
- [cell 재사용 오류](https://baechukim.tistory.com/10)

[Bug] #310 셀 reuse되는 에러 fix

---

BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
BNomad/View/PlaceCheckInView/QuestCollectionViewCell.swift

- #320 
- 현재 시간과 밋업 시간을 비교해서 밋업 시간이 이전이면 해당 밋업 셀 배경을 회색으로 만들고, 선택 시 지난 밋업이라는 alert가 뜨게 했습니다.
- @YeeunKim-archive 모임 시간이 지난 밋업 셀에 대한 피그마 프로토타입이 없어서 우선 배경만 nomadGray3으로 바꾸는 것으로 했습니다. 또, 지난 밋업 선택 시 alert와 문구는 제가 임의로 넣은 것인데, 아예 아무것도 안뜨고 선택도 안되는 것이 좋을지.. 협의 필요할 것 같습니다. 
- @sunshiningsoo 오전에 이야기한 `guard (meetUpViewModels?[indexPath.item]) != nil else { return }` 부분(@limhyoseok 밋업 데이터 바인딩 시 작성)을 건드렸습니다. 제가 확인할 때는 잘 동작하는 것 같은데 확인 부탁드립니다.
- [Date끼리 비교](https://wiwi-pe.tistory.com/214)

[Feat] #320 밋업 모임 시간 지나면 회색 & 선택 시 alert

---

BNomad/View/MeetUpView/NewMeetUpViewController.swift
BNomad/View/SettingView/PlaceRequestViewController.swift
BNomad/View/SettingView/RequestTextField.swift
BNomad/View/SettingView/SettingViewController.swift

- #303 
- NewMeetUpView, PlaceRequestView에서 화면 하단의 입력칸을 키보드가 가리는 문제를 해결했습니다.
- 피그마 프로토타입 고려하여 일부 UI 수정하였습니다.
- `PlaceRequestView`의 `UITextFieldDelegate`에서 입력칸의 y좌표를 구하기 위해 `configUI()` 함수 안에 생성했던 stack들을 밖에 프로퍼티로 꺼냈습니다.
- 유저가 위에서부터 입력칸에 작성해 나갈 때, 키보드가 가리지 않는 상단의 textField 활성화 시 키보드가 올라올 때 키보드 높이(기기마다 다름)가 구해지고, 그 다음 화면 하단의 입력칸에 작성할 때 키보드 높이(키보드 상단 y좌표)와 입력칸 하단의 y좌표 차이만큼 전체 뷰를 위로 올리고 있습니다. 
- 그래서 유저가 `NewMeetUpView`, `PlaceRequestView`에 접근하자마자 맨 아래칸부터 탭하는 경우 뷰가 키보드 위로 올라가지 않습니다.. 
- 지금처럼 한번 키보드를 올려서 기기마다 다른 키보드 높이(iPhone8: 260, iPhone14: 336, ...)를 구하는 것이 아니라 그냥 키보드 높이를 특정 값(350..?)이라고 고정하면 유저가 바로 화면 하단 입력칸을 탭하더라도 뷰가 올라가긴 할 것인데.. 좋은 방법은 아닌 것 같습니다ㅜㅜ
- 일단은 위에서부터 순서대로 입력한다고 생각하고 그대로 진행했습니다.
<p list="left">
</p>

[Bug] #303 밋업생성뷰, 장소제안뷰 키보드가 입력칸 가리는 문제 해결

---

BNomad/View/MeetUpView/MeetUpViewController.swift

- #322 
- 밋업 모집인원이 다 찼을 때 참여하기 - 확인을 누르면 참여할 수 없다는 alert가 뜨도록 했습니다.
- 밋업 상세보기로 들어갈 때 가져오는 `meetUpViewModel`의 `currentPeopleUids.count`와 `maxPeopleNum`을 단순 비교하여 참여/불가를 구분했습니다. 이전에 @limhyoseok 가 이야기한 것처럼 여러사람이 동시에 참여하기를 누르는 경우는 이걸로 제한할 수 없을 것 같고, 추가적인 조치가 필요할 것 같습니다.

[Feat] #322 밋업 모집인원 다 차면 참여불가

---

BNomad/View/MapView/MapViewController.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
BNomad/View/ReviewView/ReviewListViewController.swift

- #327 
- 이유: 체크인 버튼을 계속 초기화해주어야 하는데, 그러지 못해서 버튼들이 계속 누적되어서 쌓이고 있었음
REF: https://zeddios.tistory.com/111

[Bug] #327 체크인 버튼 crash 오류 수정 + ReviewListView 연결

---

BNomad/API/FirebaseManager.swift
BNomad/Application/SceneDelegate.swift

- 불필요한 네트워크 비용을 줄이기 위해서 캐시 처리를 했습니다.
- 실시간으로 변경이 필요한 meetUpPlace 부분은 캐시 처리를 제외시켰습니다.
- 캐시 처리로 인해 오프라인에서도 작동을 합니다.
- meetUpPlace를 제외하고는 동기화 속도가 느려질 수 있습니다.

[Feat] 파이어 베이스 캐시 처리

---

BNomad/View/MapView/MapViewController.swift
BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift

- #314 
- 아이콘 변경, 스팟 골라보기 선택 시 색상 변경하여 선택 중임을 표시
- 자동 체크아웃 위한 타이머 기능은 추후 구현
- 자동 체크아웃을 구현하는 방식을 기존에는 시간대별로 (10분? 30분?) 주기적으로 체크하려고 했는데 background에서 처리를 하려면 시간 체크 방식이 유효하지 않은 것 같습니다. (앱을 1시간만에 켰을 때 그때서 즉시 체크아웃 처리를 해준다면 애초에 10분, 30분 주기가 무의미)
- 오히려 거리를 크게 벗어났을 때 이벤트 처리를 해주는 방식이 시간대 체크보다는 의미가 있을 것 같은데, 대신 거리 체크를 하려면 위치정보 항상 제공, 백그라운드에서 위치 체크 허용 등 유저가 젠리 수준으로 받아들여야 하는 부분이 많은 것 같습니다. (아래 참조 링크들 기반으로 추가 논의 필요)
- https://developer.apple.com/documentation/corelocation/handling_location_updates_in_the_background
- https://aircook.tistory.com/entry/Location-updates-in-Background-Modes
- https://hyesunzzang.tistory.com/257

[Enhancement] Spot 아이콘 변경

---

BNomad/View/MeetUpView/MeetUpViewController.swift
BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
BNomad/View/SettingView/SettingViewController.swift

- #329 
- 밋업을 시간 순으로 정렬했습니다. (지난 밋업이 맨 나중에 보이도록)
- 지난 밋업을 누르면 참여하기/취소 버튼이 아니라 지난 모임이라는 버튼으로 나오고 눌리지 않습니다.
- 로그아웃, 체크아웃을 해도 지난 밋업은 참여 취소가 되지 않습니다.
- 체크아웃 시 Firebase.shared 함수가 4중, 5중으로 들어가 있습니다..

[Feat] #329 지난 밋업 관련 수정

---

BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift

- #343 
- 디자인 수정에 따라 CustomModalView에서 체크인 되어있는 장소 셀의 UI를 변경했습니다.
- 피그마와 같은 값을 줘도 색이 달라 보이는데 착시일까요?ㅜㅜ

[Enhancement] #343 체크인된 장소 셀 UI 변경

---

BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift

- #341 
- 체크인뷰의 오늘의 목표 데이터 바인딩을 수정했습니다.
- 상단에 자기 자신의 자기소개가 나오고 있어서 오늘의 목표로 수정했습니다.
- 하단 노마드 목록에는 자기 자신이 제외되었는데, 오늘의 목표는 자기 자신의 것을 포함해서 표시하고 있던 것을 수정했습니다.

[Bug] #341 체크인뷰 오늘의 목표 데이터 바인딩 오류 수정

---

BNomad/API/FirebaseManager.swift
BNomad/API/FirebaseTestVC.swift
BNomad/View/MapView/MapViewController.swift

- #350 
- Place를 로드할때마다 binding체크를 해주던 이전의 코드에서 모든 place를 로드한 이후, binding 체크해주는 방향으로 바꾸어서 초기 로드 시간을 줄였습니다.
- `fetchAllPlaces()` 함수에 `async await` 로 모든 place가 로드되는 것을 보장하도록 만들어주었습니다.
- 사용하지 않을 것 같은 주석은 조금 삭제해 두었습니다.
- 비동기로 들어가야 async, await 를 사용할 수 있기에 `bindingPlaceLocationStatus()`에서 `Task`를 사용해 주었는데, 이를 제외하고 더 좋은 방법이 있다면 알려주심 감사하겠씁니다!
기존: 
현재:
- [Async Await](https://www.youtube.com/watch?v=-5kIzkBqAzc&t=20s)

[Enhancement] #350 annotation load 로드 시간 단축

---

BNomad.xcodeproj/project.pbxproj
BNomad/View/MeetUpView/ParticipantCell.swift
BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
BNomad/View/PlaceCheckInView/QuestCollectionViewCell.swift
BNomad/View/PlaceInfoView/ReviewSubCell/ReviewSubCell.swift
BNomad/View/ProfileUIImageView.swift
BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
BNomad/View/ProfileView/ProfileViewController.swift
BNomad/View/ProfileView/VisitCardHeaderCollectionView.swift
BNomad/View/ReviewView/ReviewCell.swift
BNomad/View/SignUpView/SignUpViewController.swift

- #352 
- 회원가입시(SignUpVIewController) + 프로필 변경(ProfileEditViewController), scaleAspectFill로 되지 않은 것들을 교체해 주었습니다.
- 프로필 이미지가 들어가는 UIImageView부분이 width, height를 제외하면 동일한 부분이 많아서 프로필 이미지만 따로 관리하는 ProfileUIImageView를 만들어 주었습니다.
- 위처럼 생성할때, 이미지 프레임의 width값을 주면 cornerRadius 알아서 계산함
- 프로필 이미지가 없는 경우를 대비해, default 이미지를 넣었습니다.
- init 값으로 frame의 width값을 받는게 괜찮을까요? 더 좋은 방법이 있을 것만 같습니다..
- 하다보니까 전체적으로 다듬어야 될 부분이 많이 보이네요ㅎㅎ,,,

[Bug+Enhancement] 프로필 이미지를 위한 class 만들고, UIImageView들 교체
